
language: "xx"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
  "analyzer": 'char_wb'
  "min_df": 1
  "max_df": 1.0
  "min_ngram": 1
  "max_ngram": 5
  "lowercase": true
- name: "intent_classifier_tensorflow_embedding"
